openapi: 3.0.3
info:
  title: Fiti Flaguin - OpenAPI 3.0
  description: |-
    This API does things
  termsOfService: http://swagger.io/terms/
  contact:
    email: fitiflaguin@gmail.com
  license:
    name: MIT
    url: https://choosealicense.com/licenses/mit/
  version: 0.0.1
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:5173/api/v1
tags:
  - name: phrases
    description: Everything about Phrases
  - name: likes
    description: Everything about Likes
paths:
  /phrases:
    get:
      tags:
        - phrases
      summary: Returns list of phrases
      operationId: getPhrases
      responses:
        "200":
          description: successful
          content:
            application/json:
              schema:
                type: array
                maxItems: 1000
                items:
                  $ref: "#/components/schemas/Phrase"
        "401":
          description: unauthorized
      security:
        - cookieAuth: []
    post:
      tags:
        - phrases
      summary: Creates new phrase
      operationId: createPhrase
      requestBody:
        $ref: "#/components/requestBodies/UpsertPhrase"
      responses:
        "200":
          description: successful
        "401":
          description: unauthorized
      security:
        - cookieAuth: []
  /phrases/{phraseId}:
    get:
      tags:
        - phrases
      summary: Find phrase by ID
      operationId: getPhrase
      parameters:
        - name: phraseId
          in: path
          description: ID of phrase that needs to be fetched
          required: true
          schema:
            type: number
      responses:
        "200":
          description: successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Phrase"
        "401":
          description: unauthorized
        "404":
          description: Phrase not found
      security:
        - cookieAuth: []
    put:
      tags:
        - phrases
      summary: Update a phrase by ID
      operationId: updatePhrase
      parameters:
        - name: phraseId
          in: path
          description: ID of phrase that needs to be update
          required: true
          schema:
            type: number
      requestBody:
        $ref: "#/components/requestBodies/UpsertPhrase"
      responses:
        "200":
          description: successful
        "401":
          description: unauthorized
        "404":
          description: not found
      security:
        - cookieAuth: []
    delete:
      tags:
        - phrases
      summary: Delete a phrase by ID
      operationId: deletePhrase
      parameters:
        - name: phraseId
          in: path
          description: ID of the phrase that needs to be deleted
          required: true
          schema:
            type: number
      responses:
        "204":
          description: no content
        "401":
          description: unauthorized
      security:
        - cookieAuth: []
  /phrases/{phrasesId}/likes:
    get:
      tags:
        - phrases
        - likes
      summary: Returns phrase's likes by ID
      description: Returns the list phrase's likes
      operationId: getPhraseLikes
      parameters:
        - name: phraseId
          in: path
          description: ID of phrase that needs to be fetched
          required: true
          schema:
            type: number
      responses:
        "200":
          description: successful
          content:
            application/json:
              schema:
                type: array
                maxItems: 1000
                items:
                  $ref: "#/components/schemas/Like"
        "401":
          description: unauthorized
        "404":
          description: not found
      security:
        - cookieAuth: []
    put:
      tags:
        - phrases
        - likes
      summary: Create a phrase's like by ID for given user
      operationId: createPhraseLike
      parameters:
        - name: phraseId
          in: path
          description: ID of phrase of the like that needs to be created
          required: true
          schema:
            type: number
      responses:
        "200":
          description: successful
        "401":
          description: unauthorized
        "404":
          description: not found
      security:
        - cookieAuth: []
    delete:
      tags:
        - phrases
        - likes
      summary: Delete phrase's like by ID for the current user
      operationId: deletePhraseLike
      parameters:
        - name: phraseId
          in: path
          description: ID of the phrase of the like that needs to be deleted
          required: true
          schema:
            type: number
      responses:
        "204":
          description: no content
        "401":
          description: unauthorized
        "404":
          description: not found
      security:
        - cookieAuth: []
components:
  schemas:
    Phrase:
      type: object
      properties:
        id:
          type: number
        content:
          type: string
          example: Content
        user_id:
          type: string
          format: uuid
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    Like:
      type: object
      properties:
        phrase_id:
          type: number
        user_id:
          type: string
          format: uuid
        created_at:
          type: string
          format: date-time
  requestBodies:
    Phrase:
      description: Phrase object
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Phrase"
    UpsertPhrase:
      description: Phrase creation and update object
      content:
        application/x-www-form-urlencoded:
          schema:
            type: object
            properties:
              content:
                type: string
                example: Content
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: supabase-auth-token
