openapi: 3.0.3
info:
  title: Fiti Flaguin - OpenAPI 3.0
  description: |-
    This API does things
  termsOfService: http://swagger.io/terms/
  contact:
    email: fitiflaguin@gmail.com
  license:
    name: MIT
    url: https://choosealicense.com/licenses/mit/
  version: 0.0.1
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:5173/api/v1
tags:
  - name: phrases
    description: Everything about your Phrase
paths:
  /phrases:
    get:
      tags:
        - phrases
      summary: Returns phrases
      description: Returns a list of phrases
      operationId: getPhrases
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Phrase"
      security:
        - cookieAuth: []
    post:
      tags:
        - phrases
      summary: Creates new phrase
      description: Creates a new phrase
      operationId: createPhrase
      requestBody:
        $ref: "#/components/requestBodies/UpsertPhrase"
      responses:
        "200":
          description: successful operation
      security:
        - cookieAuth: []
  /phrases/{phraseId}:
    get:
      tags:
        - phrases
      summary: Find phrase order by ID
      operationId: getPhraseById
      parameters:
        - name: phraseId
          in: path
          description: ID of order that needs to be fetched
          required: true
          schema:
            type: number
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Phrase"
        "404":
          description: Phrase not found
      security:
        - cookieAuth: []
    put:
      tags:
        - phrases
      summary: Create a phrase with given ID
      operationId: createPhraseByID
      parameters:
        - name: phraseId
          in: path
          description: ID of order that needs to be fetched
          required: true
          schema:
            type: number
      requestBody:
        $ref: "#/components/requestBodies/UpsertPhrase"
      responses:
        "200":
          description: successful operation
        "404":
          description: Phrase not found
      security:
        - cookieAuth: []
    delete:
      tags:
        - phrases
      summary: Delete phrase order by ID
      operationId: deletePhraseByID
      parameters:
        - name: phraseId
          in: path
          description: ID of the order that needs to be deleted
          required: true
          schema:
            type: number
      responses:
        "204":
          description: successful operation
      security:
        - cookieAuth: []
components:
  schemas:
    Phrase:
      type: object
      properties:
        id:
          type: number
        content:
          type: string
          example: Content
        user_id:
          type: string
          format: uuid
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    CreatePhrase:
      type: object
      properties:
        content:
          type: string
          example: Content
  requestBodies:
    Phrase:
      description: Phrase object
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Phrase"
    UpsertPhrase:
      description: Phrase creation and update object
      content:
        application/x-www-form-urlencoded:
          schema:
            $ref: "#/components/schemas/CreatePhrase"
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: supabase-auth-token
